var cheeto = require('../cheeto').cheeto()
console.log(cheeto.get('http://npmjs.org'))
console.log(cheeto.isValid(['is','http://heroku.com','http://beepboop.net','cropdust']))
console.log(cheeto.isValid('mean'))
console.log(cheeto.isValid('http://nodeschool.io'))
